"""Process steps updated

Revision ID: a796fe7e1947
Revises: 4a4239857acd
Create Date: 2025-07-26 12:21:41.228044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a796fe7e1947'
down_revision: Union[str, Sequence[str], None] = '4a4239857acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_steps', sa.Column('text', sa.String(), nullable=False))
    op.add_column('process_steps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('process_steps', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'process_steps', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_steps', type_='foreignkey')
    op.drop_column('process_steps', 'order_id')
    op.drop_column('process_steps', 'updated_at')
    op.drop_column('process_steps', 'text')
    # ### end Alembic commands ###
