"""Adding phone identifier to orders table

Revision ID: e5d493176167
Revises: 647a4b2e029c
Create Date: 2025-07-04 22:58:48.323324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d493176167'
down_revision: Union[str, Sequence[str], None] = '647a4b2e029c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone_identifier', sa.String(), nullable=False))
    op.drop_index(op.f('ix_orders_plate_number'), table_name='orders')
    op.create_index(op.f('ix_orders_phone_identifier'), 'orders', ['phone_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_phone_identifier'), table_name='orders')
    op.create_index(op.f('ix_orders_plate_number'), 'orders', ['plate_number'], unique=False)
    op.drop_column('orders', 'phone_identifier')
    # ### end Alembic commands ###
